/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.basex;

import com.mycompany.basex.number_systems.Decimal;
import com.mycompany.basex.solutions.DecToBin;
import javax.swing.JRootPane;

/**
 *
 * @author LENOVO
 */
public class DecimalFrame extends javax.swing.JFrame {

    private Decimal decimal;

    /**
     * Creates new form DecimalFrame
     */
    public DecimalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        decimalPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        decimalTextField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        octBtn = new javax.swing.JButton();
        binaryBtn = new javax.swing.JButton();
        hexBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(180, 181, 181));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        jLabel1.setText("Decimal");

        decimalTextField.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        decimalTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                decimalTextFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout decimalPanelLayout = new javax.swing.GroupLayout(decimalPanel);
        decimalPanel.setLayout(decimalPanelLayout);
        decimalPanelLayout.setHorizontalGroup(
            decimalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(decimalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(decimalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );
        decimalPanelLayout.setVerticalGroup(
            decimalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(decimalPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(decimalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(decimalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        octBtn.setBackground(new java.awt.Color(0, 102, 255));
        octBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        octBtn.setForeground(new java.awt.Color(255, 255, 255));
        octBtn.setText("Octal");
        octBtn.setToolTipText("Convert Decimal to Binary");
        octBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        octBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                octBtnMouseReleased(evt);
            }
        });

        binaryBtn.setBackground(new java.awt.Color(0, 102, 255));
        binaryBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        binaryBtn.setForeground(new java.awt.Color(255, 255, 255));
        binaryBtn.setText("Binary");
        binaryBtn.setToolTipText("Convert Decimal to Binary");
        binaryBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        binaryBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                binaryBtnMouseReleased(evt);
            }
        });

        hexBtn.setBackground(new java.awt.Color(0, 102, 255));
        hexBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        hexBtn.setForeground(new java.awt.Color(255, 255, 255));
        hexBtn.setText("Hexadecimal");
        hexBtn.setToolTipText("Convert Decimal to Binary");
        hexBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hexBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                hexBtnMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(octBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(binaryBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(hexBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(octBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(binaryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(197, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(104, 104, 104)
                    .addComponent(hexBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(109, Short.MAX_VALUE)))
        );

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel2.setText("Convert to");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(decimalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel2)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(decimalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void octBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_octBtnMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_octBtnMouseReleased

    private void decimalTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_decimalTextFieldKeyTyped
        // TODO add your handling code here:
        
        char enter = evt.getKeyChar();
        if (!(Character.isDigit(enter)) && !(decimalTextField.getText().length() >= 10)) {
            evt.consume();
        }
    }//GEN-LAST:event_decimalTextFieldKeyTyped

    private void binaryBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_binaryBtnMouseReleased
        // TODO add your handling code here:
        // TODO add your handling code here:
        String decimalTxt = decimalTextField.getText();
        if (decimalTxt.isEmpty()) {
            return;
        }
        decimal = new Decimal(decimalTxt);
        DecToBin dTB = new DecToBin(decimal.decToBin());
        Object[][] rows = (Object[][]) decimal.decToBinSolution();
        dTB.addRowToTable(rows);
        dTB.setVisible(true);
    }//GEN-LAST:event_binaryBtnMouseReleased

    private void hexBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hexBtnMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_hexBtnMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DecimalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DecimalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DecimalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DecimalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DecimalFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton binaryBtn;
    private javax.swing.JPanel decimalPanel;
    private javax.swing.JTextField decimalTextField;
    private javax.swing.JButton hexBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton octBtn;
    // End of variables declaration//GEN-END:variables
}
